"""Add brand field to Product

Revision ID: 13feb261f49a
Revises: dcc7bda0c47a
Create Date: 2025-04-14 21:37:00.814387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13feb261f49a'
down_revision = 'dcc7bda0c47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('purchase_price')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.drop_constraint('sales_store_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sales_employee_id_fkey', type_='foreignkey')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('store_id')
        batch_op.drop_column('total')
        batch_op.drop_column('sale_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('sales_employee_id_fkey', 'employees', ['employee_id'], ['employee_id'])
        batch_op.create_foreign_key('sales_store_id_fkey', 'stores', ['store_id'], ['store_id'])
        batch_op.drop_column('date')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
