"""Fix conflict of backref names between Sale and SaleItem

Revision ID: 896e9335df5a
Revises: c5a6a1a5775d
Create Date: 2025-04-14 21:41:38.293237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896e9335df5a'
down_revision = 'c5a6a1a5775d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['store_id'])
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['employee_id'])
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('store_id')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('total')
        batch_op.drop_column('sale_date')

    # ### end Alembic commands ###
