"""Fix conflicting backref between Product and SaleItem

Revision ID: c5a6a1a5775d
Revises: 13feb261f49a
Create Date: 2025-04-14 21:39:14.215205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a6a1a5775d'
down_revision = '13feb261f49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('purchase_price')

    # ### end Alembic commands ###
