"""Add customers and orders tables

Revision ID: f6e62922b049
Revises: 
Create Date: 2025-04-14 19:05:16.433656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6e62922b049'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('order_items',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.drop_table('inventory_check')
    op.drop_table('product')
    op.drop_table('promotions')
    op.drop_table('sales_report')
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.alter_column('min_purchase',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('discount_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('store_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.alter_column('from_store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('to_store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('sale_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('store_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sale_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('to_store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('from_store_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('store_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.alter_column('discount_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
        batch_op.alter_column('min_purchase',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    op.create_table('sales_report',
    sa.Column('report_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('total_sales', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_items', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], name='sales_report_store_id_fkey'),
    sa.PrimaryKeyConstraint('report_id', name='sales_report_pkey')
    )
    op.create_table('promotions',
    sa.Column('promotion_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('discount_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('promotion_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('promotion_id', name='promotions_pkey')
    )
    op.create_table('product',
    sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('product_id', name='product_pkey')
    )
    op.create_table('inventory_check',
    sa.Column('check_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accounted_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actual_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('difference', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('check_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name='inventory_check_product_id_fkey'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], name='inventory_check_store_id_fkey'),
    sa.PrimaryKeyConstraint('check_id', name='inventory_check_pkey')
    )
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
